spring:
  security:
    user:
      name: admin
      password: 1234
  thymeleaf:
    prefix : classpath:/templates/
    cache: false
  #    suffix: .html
  #    cache: false
  datasource:
    hikari:
      pool-name: Leader
      jdbc-url: jdbc:postgresql://localhost:5432/mart
      username: admin
      password: admin
      maximum-pool-size: 5
      minimum-idle: 5
      driver-class-name: org.postgresql.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create        # DB (none, create, create-drop, update, validate)
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    bean: jasyptStringEncryptor